// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP2_POO2.Model;

#nullable disable

namespace TP2_POO2.Migrations
{
    [DbContext(typeof(TP2_POO2Context))]
    [Migration("20240421134841_TP2_POO2DB")]
    partial class TP2_POO2DB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP2_POO2.Model.Client", b =>
                {
                    b.Property<int>("clientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clientId"));

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("civilite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateNaissance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oenologueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clientId");

                    b.HasIndex("oenologueId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            clientId = 1,
                            adresse = "12",
                            civilite = "Monsieur",
                            dateNaissance = "2003/10/24",
                            nom = "Samuel",
                            oenologueId = "1",
                            pays = "Canada",
                            prenom = "Samuel",
                            province = "Québec",
                            ville = "Lévis"
                        });
                });

            modelBuilder.Entity("TP2_POO2.Model.Oenologue", b =>
                {
                    b.Property<string>("oenologueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppMDP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("civilite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateNaissance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("oenologueId");

                    b.ToTable("Oenologues");

                    b.HasData(
                        new
                        {
                            oenologueId = "1",
                            AppMDP = "1234",
                            adresse = "12",
                            civilite = "Monsieur",
                            dateNaissance = "2003/10/24",
                            nom = "Samuel",
                            pays = "Canada",
                            prenom = "Samuel",
                            province = "Québec",
                            ville = "Lévis"
                        });
                });

            modelBuilder.Entity("TP2_POO2.Model.Vin", b =>
                {
                    b.Property<int>("vinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vinId"));

                    b.Property<string>("acideCitrique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("acideVolatile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alcool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("sulphate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vinId");

                    b.HasIndex("clientId");

                    b.ToTable("Vins");

                    b.HasData(
                        new
                        {
                            vinId = 1,
                            acideCitrique = "0.25",
                            acideVolatile = "0.6",
                            alcool = "9.8",
                            clientId = 1,
                            sulphate = "0.53"
                        });
                });

            modelBuilder.Entity("TP2_POO2.Model.Client", b =>
                {
                    b.HasOne("TP2_POO2.Model.Oenologue", "Oenologue")
                        .WithMany("Clients")
                        .HasForeignKey("oenologueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oenologue");
                });

            modelBuilder.Entity("TP2_POO2.Model.Vin", b =>
                {
                    b.HasOne("TP2_POO2.Model.Client", "Client")
                        .WithMany("Vins")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TP2_POO2.Model.Client", b =>
                {
                    b.Navigation("Vins");
                });

            modelBuilder.Entity("TP2_POO2.Model.Oenologue", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
